{
 "title": "Dashboard project data engineering 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mardown Dashboard",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Grafana Dashboard of Data Engineering Project\n\n### Made by Marc-Antoine BOCK and Tanguy PELLERIN\n\nThis dashboard contains different monitoring metrics for our Flask Redis Search Twitter Application"
   }
  },
  {
   "title": "Number of application requests in total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flask_redis_search_twitter_app_requests_total"
    }
   ]
  },
  {
   "title": "The percentage of usage space on the pointed disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes / node_filesystem_size_bytes * 100)"
    }
   ]
  },
  {
   "title": "Memory used by Flask Redis Search Twitter App",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"Flask Redis Search Twitter App\"}"
    }
   ]
  },
  {
   "title": "Number of Exceptions in Search App",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flask_redis_search_twitter_app_exceptions_total"
    }
   ]
  },
  {
   "title": "Average Request time in seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(flask_redis_search_twitter_app_latency_seconds_sum[5m]) / rate(flask_redis_search_twitter_app_latency_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Percentage of request that take less than 1 seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(flask_redis_search_twitter_app_latency_histogram_seconds_bucket{le=\"1.0\"} / ignoring(le) flask_redis_search_twitter_app_latency_histogram_seconds_bucket{le=\"+Inf\"} * 100)"
    }
   ]
  },
  {
   "title": "Defines how much times 95 percent of the request take time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flask_redis_search_twitter_app_latency_histogram_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Average Cpu usage by seconds in n last minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Number total of cpu usage in second for the Search Twitter App",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"Flask Redis Search Twitter App\"}"
    }
   ]
  },
  {
   "title": "Number of applications are currently in progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flask_redis_search_twitter_app_inprogress_gauge"
    }
   ]
  }
 ]
}