# my global config
global:
  scrape_interval: 10s 
  evaluation_interval: 10s

# for alert 
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
      - 'localhost:9090'
      
  - job_name: 'node_exporter'
    static_configs:
    - targets:
      - 'localhost:9100'

  - job_name: 'Flask Redis Search Twitter App'
    static_configs:
    - targets:
      - 'localhost:8050'

  - job_name: 'cAdvisor'
    static_configs:
    - targets:
      - 'localhost:8082'
